[package]
name = "valence-coprocessor-domain-prover-circuit"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "The Valence co-processor circuit definition."

[dependencies]
valence-coprocessor.workspace = true
